#!/usr/bin/env python

#--- Option parsing ---#
"""
tree_edit: scripts from the Island of Lost Scripts

Usage:
  tree_edit [options] <command> [<args>...]
  tree_edit -h | --help
  tree_edit --version

Options:
  -p --perldoc  Get perldoc of command.
  -h --help     Show this screen.
  --version     Show version.

Commands:
  adaptML_get_pop
  adaptML_hab-mtx_convert
  adaptML_name_tree
  adaptML_niche_transition
  add_attribute
  attribute_edit
  bootMapper
  brlen_mod
  brlen_transform
  cat
  collapse_tips
  convert
  dist_from_root
  edit_leaves
  expand
  get_names
  get_names
  HiDe_clean_trees
  HiDe_tree_cleaner
  iTOL_downloader
  iTOL_uploader
  ladderize
  lca_finder
  makeCOGMetadata
  multi2di
  multi_newick2nexus
  nameGeneBySpecies
  nodeByCladeTable
  prune
  PruneByAbundance
  PruneByAbundance
  randomize_leaves
  rename_addCladeName
  rm_brlen
  ultrametric

Description:
  This is the main command to call various scripts associated with this project.
"""

import os, sys
from docopt import docopt
from subprocess import call

scriptDir = os.path.dirname(__file__)
subcmdDir = os.path.join(scriptDir, 'bin')

if __name__ == '__main__':
    args = docopt(__doc__,
                  version='0.1',
                  options_first=True)


    # subcommand script
    exts = ['.pl', '.py', '.r']
    scriptFiles = [os.path.join(subcmdDir, args['<command>'] + ext) for ext in exts]
    scriptFiles = filter(os.path.isfile, scriptFiles)
    if len(scriptFiles) < 1:
        exit('"{}" is not a valid command. See "tree_edit -h".'.format(args['<command>']))

    
    # calling subcommand script
    cmd = [scriptFiles[0]] + args['<args>']
    if args['--perldoc']:
        cmd = ['perldoc'] + cmd    
    exit(call(cmd))
